### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by MDorado** [Code-Sharp/uHttpSharp#27]
I've tried generating a .cer with OpenSSL and running the current code, but SSL support seems not to work.

**Comment by MDorado** [comment]
Could make it work, was not using an appropriate cert.

**Comment by ThranMaru** [comment]
Could you advise me what constitutes an appropriate cert.?

**Comment by MDorado** [comment]
I followed this to generate a correct SSL certificate:

https://www.humankode.com/asp-net-core/develop-locally-with-https-self-signed-certificates-and-asp-net-core
