### ISSUE TITLE
Disable Console messages

### ISSUE THREAD

**Issue by Memphizzz** [Code-Sharp/uHttpSharp#34]
Hi,

is there a way to disable the console [INFO] messages?

Thanks in advance!

**Comment by shanielh** [comment]
Hi.

This library is not maintained anymore, we use LibLog, and you can set the log provider in order to change the logging library to the one you use: https://github.com/Code-Sharp/uHttpSharp/blob/master/uhttpsharp/App_Packages/LibLog.3.1/LibLog.cs#L409
